name: Artifacts

on:
  push:
    branches:
      - main

jobs:
  image:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  archive:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Compile lambda
        run: go build -o main main.go
      - name: Package binary
        run: zip main.zip main
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'main.zip'
          default_author: github_actions
          message: 'Update main.zip'
